/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 17
#define YY_END_OF_BUFFER 18
static yyconst short int yy_acclist[47] =
    {   0,
       18,   15,   17,    1,   15,   17,    1,   17,   17,   11,
       17,   15,   17,    2,   17,   16,   17,    6,   17,    6,
       17,    1,   14,   13,   11,   10,   16,   13,   11,   11,
       10,   10,   10,    3,    4,   10,    4,   10,    4,    5,
       12,    9,    8,    9,    8,    7
    } ;

static yyconst short int yy_accept[117] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   10,
       12,   14,   16,   18,   20,   22,   23,   23,   24,   25,
       26,   26,   27,   27,   27,   27,   28,   28,   29,   30,
       30,   30,   30,   30,   30,   30,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       32,   32,   32,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   34,   34,   34,   34,
       34,   34,   34,   34,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   39,   39,   40,   40,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       42,   42,   42,   42,   42,   42,   42,   43,   43,   44,
       44,   45,   46,   46,   47,   47
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,   10,
       11,   12,    1,    1,   13,   14,   15,   14,   16,   14,
       14,   14,   14,   14,   14,   14,   17,   18,   19,   14,
       14,   14,   14,   20,   14,   14,   14,   14,   14,   14,
        1,    1,    1,    1,    1,    1,   21,   22,   23,   22,

       24,   22,   22,   22,   25,   22,   22,   26,   27,   28,
       29,   30,   22,   31,   32,   33,   22,   22,   22,   22,
       34,   22,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[35] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static yyconst short int yy_base[127] =
    {   0,
        0,    0,  253,  252,  261,  264,   33,   36,  255,   34,
       30,  264,    0,  264,  251,   42,  253,  252,  247,   41,
      243,  264,   37,   39,   42,    0,  222,  244,   49,   40,
       47,   52,   54,  229,  242,   60,   58,   56,   49,   60,
      219,  240,   70,   75,   64,   67,  223,  238,   78,  231,
       89,   93,  222,   94,   77,  232,  213,  236,  226,   80,
       97,  217,   84,   99,  116,  229,  205,  228,  103,  117,
      102,  121,  123,  224,  224,  217,  210,  201,  116,  131,
      115,  137,  192,  189,  188,  167,  264,  189,  126,  147,
      128,  152,  163,  186,  138,  154,  135,  164,  159,  264,

      153,  167,  148,  180,  146,  173,  174,  179,  182,  121,
      124,   91,   91,  264,  264,  205,  208,  211,   81,  214,
      217,  220,  223,  226,  229,  232
    } ;

static yyconst short int yy_def[127] =
    {   0,
      115,    1,  116,  116,  115,  115,  115,  115,  117,  115,
      118,  115,  119,  115,  115,  115,  117,  117,  115,  115,
      118,  115,  118,  118,  118,  119,  115,  115,  115,  118,
      118,  118,  118,  115,  115,  115,  118,  118,  118,  118,
      115,  115,  120,  121,  118,  118,  115,  115,  120,  122,
      120,  121,  123,  121,  118,  118,  115,  115,  122,  122,
      120,  123,  123,  121,  124,  125,  115,  115,  122,  120,
      123,  121,  124,  126,  125,  115,  115,  115,  122,  120,
      123,  121,  126,  126,  126,  115,  115,  115,  122,  120,
      123,  121,  115,  115,  122,  120,  123,  121,  115,  115,

      122,  120,  123,  121,  115,  122,  120,  123,  121,  115,
      122,  123,  115,  115,    0,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115
    } ;

static yyconst short int yy_nxt[299] =
    {   0,
        6,    7,    7,    8,    9,    6,    6,    6,   10,   11,
        6,    6,   12,   12,   12,   12,   12,   12,   12,   12,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   16,   16,   16,   16,   16,   16,
       19,   22,   20,   16,   16,   16,   23,   19,   22,   29,
       22,   22,   30,   22,   35,   19,   24,   36,   22,   37,
       22,   25,   31,   22,   32,   22,   19,   22,   36,   22,
       43,   22,   21,   45,   33,   22,   44,   21,   22,   38,
       21,   50,   39,   26,   51,   46,   53,   40,   22,   50,
       56,   21,   51,   55,   60,   21,   21,   54,   69,   21,

       50,   21,  114,   51,   53,   53,   63,   61,   50,   65,
       53,   51,   71,   63,   70,   54,   54,   60,   21,   21,
       79,   54,   64,   21,   63,   21,   72,   74,   50,   81,
       60,   51,   53,   21,   83,   89,   80,   63,   60,   21,
       60,   95,   50,   54,  113,   51,   90,   91,   53,   21,
       63,   97,   60,   82,   21,  101,   21,   63,   50,   54,
       92,   51,  103,   53,   96,   50,   21,   60,   51,   21,
       63,  110,  106,  102,   54,   53,   21,  107,   50,   98,
      108,   51,   21,  111,   21,   50,   54,   60,   51,  112,
      109,   53,  105,   53,  100,   99,  104,   94,   93,   85,

       85,   63,   54,   85,   54,   14,   14,   14,   17,   88,
       17,   21,   21,   21,   49,   49,   49,   52,   52,   52,
       59,   87,   59,   62,   86,   62,   73,   73,   73,   75,
       75,   75,   84,   76,   84,   85,   78,   77,   76,   63,
       60,   68,   67,   66,   63,   60,   58,   57,   48,   47,
       42,   41,   28,   34,   22,   28,   18,   18,   27,   18,
      115,   15,   15,    5,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115

    } ;

static yyconst short int yy_chk[299] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    7,    7,    8,    8,    8,
       10,   11,   10,   16,   16,   16,   11,   20,   23,   20,
       24,   30,   23,   25,   29,   29,   11,   29,   31,   30,
       39,   11,   24,   32,   25,   33,   36,   38,   36,   37,
       37,   40,   43,   39,   25,   45,   38,   44,   46,   31,
       49,   43,   32,  119,   43,   40,   44,   33,   55,   49,
       46,   51,   49,   45,   60,   52,   54,   44,   60,   61,

       51,   64,  113,   51,   52,   54,   63,   51,   61,   55,
       64,   61,   63,  112,   61,   52,   54,   69,   65,   70,
       69,   64,   54,   72,   71,   73,   64,   65,   70,   71,
       79,   70,   72,   80,   73,   79,   70,   81,  111,   82,
       89,   89,   80,   72,  110,   80,   80,   81,   82,   90,
       91,   91,   95,   72,   92,   95,   96,   97,   90,   82,
       82,   90,   97,   92,   90,   96,   98,  101,   96,  102,
      103,  105,  101,   96,   92,   98,  107,  102,  102,   92,
      103,  102,  104,  106,  109,  107,   98,  106,  107,  108,
      104,  104,   99,  109,   94,   93,   98,   88,   86,   85,

       84,  108,  104,   83,  109,  116,  116,  116,  117,   78,
      117,  118,  118,  118,  120,  120,  120,  121,  121,  121,
      122,   77,  122,  123,   76,  123,  124,  124,  124,  125,
      125,  125,  126,   75,  126,   74,   68,   67,   66,   62,
       59,   58,   57,   56,   53,   50,   48,   47,   42,   41,
       35,   34,   28,   27,   21,   19,   18,   17,   15,    9,
        5,    4,    3,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "retrieve.flex"
#define INITIAL 0
#line 6 "retrieve.flex"

#include <iostream>
#include <vector>    
#include <fstream>
#include <string>
#include <algorithm>
#include <sstream>
#include <string.h>
#include <regex>
#include "hashtable.h"
extern int yylex(void);
using namespace std;

#undef yywrap

char Ch; char newLine;
string token; string stemmedToken;
int i = 0; int doc_freq = 0; int token_num = 0;
bool only_whitespace = true; bool reset = true;

// Vector created for finding the stop words
vector<string> stop_words = {"about","an","and","are","as","at","be","by","com","for","from","how","in","is","it","of","on","or","that","the","this","to","was","what","when","where","who","will","with","the","www","text","type","content","date","html","server","gmt"};
bool stop = false;

vector<string> query;
vector<string> quoteQueries;


bool checkForVowel(char vowel) {
   if (vowel == 'a')
      return true;
   if (vowel == 'e')
      return true;
   if (vowel == 'i')
      return true;
   if (vowel == 'o')
      return true;
   if (vowel == 'u')
      return true;
   return false;
}

bool checkForPreviousVowel(char token[]) {
   int b = 0;
   bool flag = false;
   while (!flag) {
      char checkVowel = token[b];
      if (checkForVowel(checkVowel)) {
         flag = true;
         return true;
      }
      else if (b >= strlen(token)) {
         flag = true;
         return false;
      }
      b++;
   }
}

void handleEnding(char token[]) {
   int newLength = 0;
   while (token[newLength] != '\0')
      newLength++;

   if (strcmp(token + strlen(token)-2, "at") == 0) {
      token[newLength] = 'e';
      token[newLength+1] = '\0';
   }
   else if (strcmp(token + strlen(token)-2, "bl") == 0) {
      token[newLength] = 'e';
      token[newLength+1] = '\0';
   }
   else if (strcmp(token + strlen(token)-2, "iz") == 0) {
      token[newLength] = 'e';
      token[newLength+1] = '\0';
   }
   else if (token[newLength-1] == token[newLength-2]) {
      if (!strcmp(token + strlen(token)-2, "ll") == 0) {
         if (!strcmp(token + strlen(token)-2, "ss") == 0) {
            if (!strcmp(token + strlen(token)-2, "zz") == 0) {
               token[newLength-1] = '\0';
            }
         }
      }
   }
}

//determine the number of vowel(s) followed by consonant(s) pairs there are
int m(char token[]) {
   int l = strlen(token);
   int index = 0;
   int vc = 0;
   while (index < l) {
      char a = token[index];
      if (checkForVowel(a)) {
         char b = token[index+1];
         if (!checkForVowel(b))
            vc++;
      }
      index++;
   }
   return vc;
}

void step1a(char token[], int length) {

   //hanlde sses ending
   if (strcmp(token + strlen(token)-4, "sses") == 0) {
      //replace last 2 characters with null
      token[length - 2] = '\0';
   }

   //hanlde ied ending
   else if (strcmp(token + strlen(token)-3, "ied") == 0) {
      if (strlen(token) > 4) {
         //replace last 2 characters with null
         token[length - 2] = '\0';
      }
      else {
         //replace last character with null
         token[length - 1] = '\0';
      }
   }

   //hanlde ies ending
   else if (strcmp(token + strlen(token)-3, "ies") == 0) {
      if (strlen(token) > 4) {
         //replace last 2 characters with null
         token[length - 2] = '\0';
      }
      else {
         //replace last character with null
         token[length - 1] = '\0';
      }
   }
   else if (strcmp(token + strlen(token)-1, "s") == 0) {
      char checkVowel = token[length-2];
      if (!checkForVowel(checkVowel) && checkVowel != 's') {
         if (checkForPreviousVowel(token)) {
            token[length -1] = '\0';
         }
      }
   }
}

void step1b(char token[], char token2[], int length) {

   //eed ending
   if (strcmp(token + strlen(token)-3, "eed") == 0) {
      token2[length-3] = '\0';
   
      if (m(token2) > 0 ) {
         //replace last character with null
         token[length-1] = '\0';
      }
   }

   //eedly ending
   else if (strcmp(token + strlen(token)-5, "eedly") == 0) {
      token2[length-5] = '\0';
      
      if(m(token2) > 0) {
         //replace last 3 characters with null
         token[length-3] = '\0';
      }
   }

   //ed ending
   else if (strcmp(token + strlen(token)-2, "ed") == 0) {
      token2[length-2] = '\0';
      
      if(checkForPreviousVowel(token2)) {
         //replace last 2 characters with null
         token[length-2] = '\0';

         //handle the at, bl, iz endings
         handleEnding(token);
      }
   }

   //edly ending
   else if (strcmp(token + strlen(token)-4, "edly") == 0) {
      token2[length-4] = '\0';
      
      if(checkForPreviousVowel(token2)) {
         //replace last 4 characters with null
         token[length-4] = '\0';

         //handle the at, bl, iz endings
         handleEnding(token);
      }
   }

   //ing ending
   else if (strcmp(token + strlen(token)-3, "ing") == 0) {
      token2[length-3] = '\0';
      
      if(checkForPreviousVowel(token2)) {
         //replace last 3 characters with null
         token[length-3] = '\0';

         //handle the at, bl, iz endings
         handleEnding(token);
      }
   }

   //ingly ending
   else if (strcmp(token + strlen(token)-5, "ingly") == 0) {
      token2[length-5] = '\0';
      
      if(checkForPreviousVowel(token2)) {
         //replace last 5 characters with null
         token[length-5] = '\0';

         //handle the at, bl, iz endings
         handleEnding(token);
      }
   }
}

//change y to i if there is a vowel
void step1c(char token[], char token2[], int length) {
   char a = token[0];
   if (token[length-1] == 'y') {
      token[length-1] = '\0';
      if (checkForPreviousVowel(token)) {
         token[length-1] = 'i';
         token[length] = '\0';
      }
      else {
         token[length-1] = 'y';
         token[length] = '\0';
      }
   }
}

void step2(char token[], char token2[], int length) {

   //handle ational ending
   if (strcmp(token + strlen(token)-7, "ational") == 0) {
      token2[length-7] = '\0';

      if (m(token2) > 0) {
         //replace last 4 characters with null
         token[length-4] = '\0';
         token[length-5] = 'e';
      }
   }

   //handle tional ending
   else if (strcmp(token + strlen(token)-6, "tional") == 0) {
      token2[length-6] = '\0';
      
      if (m(token2) > 0) {
         //replace last 2 characters with null
         token[length-2] = '\0';
      }
   }

   //handle enci ending
   else if (strcmp(token + strlen(token)-4, "enci") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 0) {
         //change last character to e
         token[length-1] = 'e';
      }
   }

   //handle anci ending
   else if (strcmp(token + strlen(token)-4, "anci") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 0) {
         //change last character to e
         token[length-1] = 'e';
      }
   }

   //handle izer ending
   else if (strcmp(token + strlen(token)-4, "izer") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 0) {
         //replace last character with null
         token[length-1] = '\0';
      }
   }

   //handle abli ending
   else if (strcmp(token + strlen(token)-4, "abli") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 0) {
         //change last character to e
         token[length-1] = 'e';
      }
   }

   //handle alli ending
   else if (strcmp(token + strlen(token)-4, "alli") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 0) {
         //change last 2 characters with null
         token[length-2] = '\0';
      }
   }

   //handle entli ending
   else if (strcmp(token + strlen(token)-5, "entli") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //change last 2 characters with null
         token[length-2] = '\0';
      }
   }

   //handle eli ending
   else if (strcmp(token + strlen(token)-3, "eli") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 0) {
         //change last 2 characters with null
         token[length-2] = '\0';
      }
   }

   //handle ousli ending
   else if (strcmp(token + strlen(token)-5, "ousli") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //change last 2 characters with null
         token[length-2] = '\0';
      }
   }

   //handle ization ending
   else if (strcmp(token + strlen(token)-7, "ization") == 0) {
      token2[length-7] = '\0';

      if(m(token2) > 0) {
         //replace last 4 characters with null
         token[length-4] = '\0';
         token[length-5] = 'e';
      }
   }

   //handle ation ending
   else if (strcmp(token + strlen(token)-5, "ation") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //replace last 2 characters with null
         token[length-2] = '\0';
         token[length-3] = 'e';
      }
   }

   //handle ator ending
   else if (strcmp(token + strlen(token)-4, "ator") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 0) {
         //replace last character with null
         token[length-1] = '\0';
         token[length-2] = 'e';
      }
   }

   //handle alism ending
   else if (strcmp(token + strlen(token)-5, "alism") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //replace last 3 characters with null
         token[length-3] = '\0';
      }
   }

   //handle iveness ending
   else if (strcmp(token + strlen(token)-7, "iveness") == 0) {
      token2[length-7] = '\0';

      if(m(token2) > 0) {
         //replace last 4 characters with null
         token[length-4] = '\0';
      }
   }

   //handle fulness ending
   else if (strcmp(token + strlen(token)-7, "fulness") == 0) {
      token2[length-7] = '\0';

      if(m(token2) > 0) {
         //replace last 4 characters with null
         token[length-4] = '\0';
      }
   }

   //handle ousness ending
   else if (strcmp(token + strlen(token)-7, "ousness") == 0) {
      token2[length-7] = '\0';

      if(m(token2) > 0) {
         //replace last 4 characters with null
         token[length-4] = '\0';
      }
   }

   //hanlde aliti ending
   else if (strcmp(token + strlen(token)-5, "aliti") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //replace last 3 characters with null
         token[length-3] = '\0';
      }
   }

   //handle iviti ending
   else if (strcmp(token + strlen(token)-5, "iviti") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //replace last 2 characters with null
         token[length-2] = '\0';
         token[length-3] = 'e';
      }
   }

   //handle biliti ending
   else if (strcmp(token + strlen(token)-6, "biliti") == 0) {
      token2[length-6] = '\0';

      if(m(token2) > 0) {
         //replace last 3 characters with null
         token[length-3] = '\0';
         token[length-4] = 'e';
         token[length-5] = 'l';
      }
   }
}

void step3(char token[], char token2[], int length) {
      
   //handle icate ending
   if (strcmp(token + strlen(token)-5, "icate") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //replace last 3 characters with null
         token[length-3] = '\0';
      }
   }

   //handle ative ending
   else if (strcmp(token + strlen(token)-5, "ative") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //replace last 5 characters with null
         token[length-5] = '\0';
      }
   }

   //handle alize ending
   else if (strcmp(token + strlen(token)-5, "alize") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //replace last 3 characters with null
         token[length-3] = '\0';
      }
   }

   //handle iciti ending
   else if (strcmp(token + strlen(token)-5, "iciti") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 0) {
         //replace last 3 characters with null
         token[length-3] = '\0';
      }
   }

   //handle ical ending
   else if (strcmp(token + strlen(token)-4, "ical") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 0) {
         //replace last 2 characters with null
         token[length-2] = '\0';
      }
   }

   //handle ful ending
   else if (strcmp(token + strlen(token)-3, "ful") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 0) {
         //replace last 3 characters with null
         token[length-3] = '\0';
      }
   }

   //handle ness ending
   else if (strcmp(token + strlen(token)-4, "ness") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 0) {
         //replace last 4 characters with null
         token[length-4] = '\0';
      }
   }
}

void step4(char token[], char token2[], int length) {

   //handle al ending
   if (strcmp(token + strlen(token)-2, "al") == 0) {
      token2[length-2] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 2 characters with null
         token[newLength-2] = '\0';
      }
   }

   //handle ance ending
   else if (strcmp(token + strlen(token)-4, "ance") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 4 characters with null
         token[newLength-4] = '\0';
      }
   }

   //handle ence ending
   else if (strcmp(token + strlen(token)-4, "ence") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 4 characters with null
         token[newLength-4] = '\0';
      }
   }

   //handle er ending
   else if (strcmp(token + strlen(token)-2, "er") == 0) {
      token2[length-2] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 2 characters with null
         token[newLength-2] = '\0';
      }
   }

   //handle ic ending
   else if (strcmp(token + strlen(token)-2, "ic") == 0) {
      token2[length-2] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 2 characters with null
         token[newLength-2] = '\0';
      }
   }

   //handle able ending
   else if (strcmp(token + strlen(token)-4, "able") == 0) {
      int newLength = strlen(token2);
      token2[newLength-4] = '\0';

      if(m(token2) > 1) {
         int newLength2 = strlen(token);
         //replace last 4 characters with null
         token[newLength2-4] = '\0';
      }
   }

   //handle ible ending
   else if (strcmp(token + strlen(token)-4, "ible") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 4 characters with null
         token[newLength-4] = '\0';
      }
   }

   //handle ant ending
   else if (strcmp(token + strlen(token)-3, "ant") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 3 characters with null
         token[newLength-3] = '\0';
      }
   }

   //handle ement ending
   else if (strcmp(token + strlen(token)-5, "ement") == 0) {
      token2[length-5] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 5 characters with null
         token[newLength-5] = '\0';
      }
   }

   //handle ment ending
   else if (strcmp(token + strlen(token)-4, "ment") == 0) {
      token2[length-4] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 4 characters with null
         token[newLength-4] = '\0';
      }
   }

   //handle ent ending
   else if (strcmp(token + strlen(token)-3, "ent") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 3 characters with null
         token[newLength-3] = '\0';
      }
   }

   //handle ion ending
   else if (strcmp(token + strlen(token)-3, "ion") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 1) {
         if (token2[length-4] == 's') {
            token[length-3] = '\0';
         }
         else if (token2[length-4] == 't') {
            int newLength = strlen(token);
            //replace last 3 characters with null
            token[newLength-3] = '\0';
         }
      }
   }

   //handle ou ending
   else if (strcmp(token + strlen(token)-2, "ou") == 0) {
      token2[length-2] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 2 characters with null
         token[newLength-2] = '\0';
      }
   }

   //handle ism ending
   else if (strcmp(token + strlen(token)-3, "ism") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 3 characters with null
         token[newLength-3] = '\0';
      }
   }

   //handle ate ending
   else if (strcmp(token + strlen(token)-3, "ate") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 3 characters with null
         token[newLength-3] = '\0';
      }
   }

   //handle iti ending
   else if (strcmp(token + strlen(token)-3, "iti") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 3 characters with null
         token[newLength-3] = '\0';
      }
   }

   //handle ous ending
   else if (strcmp(token + strlen(token)-3, "ous") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 3 characters with null
         token[newLength-3] = '\0';
      }
   }

   //handle ive ending
   else if (strcmp(token + strlen(token)-3, "ive") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 3 characters with null
         token[newLength-3] = '\0';
      }
   }

   //handle ize ending
   else if (strcmp(token + strlen(token)-3, "ize") == 0) {
      token2[length-3] = '\0';

      if(m(token2) > 1) {
         int newLength = strlen(token);
         //replace last 3 characters with null
         token[newLength-3] = '\0';
      }
   }
}

//remove e endings
void step5a(char token[], char token2[], int length) {
   if (strcmp(token + strlen(token)-1, "e") == 0) {
      token2[length-1] = '\0';

      if (m(token2) > 1) {
         //replace last character with null
         token[length-1] = '\0';
      }
      else if (m(token2) == 1) {
         int newLength = strlen(token2);
         int index = 1;
         bool cvcFlag = false;
         bool flag1 = false;
         bool flag2 = false;
         bool flag3 = false;

         if (!checkForVowel(token2[newLength-1])) {

            if (!token2[newLength-1] != 'w') {

               if (!token2[newLength-1] != 'x') {

                  if (!token2[newLength-1] != 'y') {

                     while(!checkForVowel(token2[newLength-index]) && !flag1) {
                        index++;
                        if (newLength-index < 0) {
                           flag1 = true;
                        }
                     }
                     while(checkForVowel(token2[newLength-index]) && !flag2) {
                        index++;
                        if (newLength-index < 0) {
                           flag2 = true;
                        }
                     }
                     while(!checkForVowel(token2[newLength-index]) && !flag3) {
                        index++;
                        flag3 = true;
                        cvcFlag = true;
                     }
                  }
               }
            }
         }

         if (!cvcFlag && strlen(token) > 3) {
            //replace last character with null
            token[length-1] = '\0';
         }
      }
   }
}

void step5b(char token[], char token2[], int length) {
   if (token[length-1] == token[length-2]) {
      if (token[length-1] == 'l') {
         token2[length-2] = '\0';
         if (m(token2) > 1) {
            //remove extra l
            token[length-1] = '\0';
         }
      }
   }
}

void PorterStemming(const string & myToken, const int recursive) {

      if (myToken.find(' ') != string::npos) {

         if (recursive == 0) {
            reset = false;
            if (stemmedToken != "")
               quoteQueries.push_back(stemmedToken);
            stemmedToken = "";
         }
         size_t spacePos = myToken.find(' ');

         string first = myToken.substr(0, spacePos);
         string second = myToken.substr(spacePos+1);

         PorterStemming(first, 1);
         PorterStemming(second, 1);
      }
      else {
         int total = 0;
         int length = myToken.length();
         char* token = new char[length + 1];
         char* token2 = new char[length + 1];
         strcpy(token, myToken.c_str());
         strcpy(token2, myToken.c_str());

         step1a(token, length);
         step1b(token, token2, length);
         step1c(token, token2, length);
         step2(token, token2, length);
         step3(token, token2, length);
         step4(token, token2, length);
         step5a(token, token2, length);
         step5b(token, token2, length);

         if(!reset) {
            string tmp = token;
            if (stemmedToken == "")
                  stemmedToken = tmp;
            else {
                  stemmedToken = stemmedToken + " " + tmp; 
            }
         }
         else {
            if (stemmedToken != "") {
               quoteQueries.push_back(stemmedToken);
               stemmedToken = "";
               reset = false;
            }
         }

         //cout << "inserting " << token << endl;
         query.push_back(token);
         token_num++;
         delete[] token;
         delete[] token2;
      }
      return;
}
#define IN_JAVASCRIPT 1

#line 1351 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 873 "retrieve.flex"

#line 1515 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 116 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 264 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 874 "retrieve.flex"
{
   char newLine = '\n'; 
   //fprintf(yyout, "%c", newLine); 
   only_whitespace = true;
   for (char c : token) {
      if (!isspace(static_cast<unsigned char>(c))) {
         only_whitespace = false;
         break;
      }
   }

   if (!only_whitespace) {
      PorterStemming(token, 0);
      token = "";
      doc_freq++;
   }
   }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 892 "retrieve.flex"
{Ch = tolower(yytext[0]); token += Ch;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 893 "retrieve.flex"
{
    BEGIN(IN_JAVASCRIPT);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 897 "retrieve.flex"
{
    BEGIN(IN_JAVASCRIPT);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 901 "retrieve.flex"
{
    BEGIN(INITIAL);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 905 "retrieve.flex"
{
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 907 "retrieve.flex"
{ 
   only_whitespace = true;
   for (char c : token) {
      if (!isspace(static_cast<unsigned char>(c))) {
         only_whitespace = false;
         break;
      }
   }

   if (!only_whitespace) {

      //Check if token is size 1 or if it is a stop word
      size_t token_size = token.size();
      stop = find(stop_words.begin(), stop_words.end(), token) != stop_words.end();
      if(token_size == 1 || stop == true) {
         token = "";
      }
      else {
         PorterStemming(token, 0);
         token = "";
         doc_freq++;
      }
   }
   }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 931 "retrieve.flex"
{;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 932 "retrieve.flex"
{;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 933 "retrieve.flex"
{if((yytext[1] == 'm' || yytext[1] == 'M') && (yytext[6] == 'n' || yytext[6] == 'N')){REJECT;};}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 934 "retrieve.flex"
{
    int i = 0; 
    while(yytext[i] >= '0' && yytext[i] <= '9') {
        token += yytext[i];i++;
    }

      //Check if token is size 1 or if it is a stop word
      size_t token_size = token.size();
      stop = find(stop_words.begin(), stop_words.end(), token) != stop_words.end();
      if(token_size == 1 || stop == true) {
         token = "";
      }
      else {
         PorterStemming(token, 0);
         token = "";
         doc_freq++;
      }
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 952 "retrieve.flex"
{
    for(int i = 0; i < 12; i++) {
        token += yytext[i];
    }
    //Check if token is size 1 or if it is a stop word
    size_t token_size = token.size();
    stop = find(stop_words.begin(), stop_words.end(), token) != stop_words.end();
    if(token_size == 1 || stop == true) {
        token = "";
    }
    else {
        PorterStemming(token, 0);
        token = "";
        doc_freq++;
    }
    newLine = '\n'; 
    fprintf(yyout, "%c", newLine); 
    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 970 "retrieve.flex"
{;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 971 "retrieve.flex"
{
    int i = 1;
    while (yytext[i] != '"') {
        token += yytext[i];
        i++;
    }
    PorterStemming(token, 0);
    token = "";
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 980 "retrieve.flex"
{
   only_whitespace = true;
   for (char c : token) {
      if (!isspace(static_cast<unsigned char>(c))) {
         only_whitespace = false;
         break;
      }
   }

   if (!only_whitespace) {

      //Check if token is size 1 or if it is a stop word
      size_t token_size = token.size();
      stop = find(stop_words.begin(), stop_words.end(), token) != stop_words.end();
      if(token_size == 1 || stop == true) {
         token = "";
      }
      else {
         PorterStemming(token, 0);
         token = "";
         doc_freq++;
      }
   }
   newLine = '\n'; 
    
   }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 1006 "retrieve.flex"
{
   int i = 0; 
   while(yytext[i] >= 'a' && yytext[i] <= 'z') {
      token += yytext[i];i++;
   } 
   only_whitespace = true;
   for (char c : token) {
      if (!isspace(static_cast<unsigned char>(c))) {
         only_whitespace = false;
         break;
      }
   }

   if (!only_whitespace) {

      //Check if token is size 1 or if it is a stop word
      size_t token_size = token.size();
      stop = find(stop_words.begin(), stop_words.end(), token) != stop_words.end();
      if(token_size == 1 || stop == true) {
         token = "";
      }
      else {
         PorterStemming(token, 0);
         token = "";
         doc_freq++;
      }
   }
   }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 1034 "retrieve.flex"
ECHO;
	YY_BREAK
#line 1824 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(IN_JAVASCRIPT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 116 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 116 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 115);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 1034 "retrieve.flex"


const unsigned long NUM_KEYS = 30872;
HashTable Ht(NUM_KEYS);

//This is a custom struct to use in my accumulator
struct Bucket {
    string document;
    int wt;
};

//This is a custom comparing function to use to sort my accumulator
bool compareWT(const Bucket &a, const Bucket &b) {
    return a.wt > b.wt;
}

//This is the function to handle the queries
void handleQuery(string dict, string post, vector<Bucket> accumulator) 
{

    //open dict/post files
    ifstream din(dict);
    ifstream pin(post);

    //For each query
    for(int i = 0; i < query.size(); i++) 
    {
        //set pointer to beginning
        din.clear();
        din.seekg(0, std::ios::beg);
        pin.clear();
        pin.seekg(0, std::ios::beg);

        //declare all variables used for the queries
        string queryWord = query[i];
        string word = "";
        int  num_docs = 0;
        int start = 0;
        int line_number = 0;
        int doc_id = 0;
        int wt = 0;
        int totalToken = 0;
        int loc_start = 0;
        string line = "";
        bool found = false;

        streampos dictPos = Ht.Find(queryWord);
        dictPos = dictPos * 32;

        din.seekg(dictPos, ios::beg);

        din >> word >> num_docs >> start;

        //when a match is found, calculate the position in bytes
        if (word == queryWord) 
        {
            found = true;
            streampos postPos = start-1;
            postPos = postPos * 23;
            
            //seek for that position
            pin.seekg(postPos, ios::beg);

            //for each document, take in the values
            for (int j = 0; j < num_docs; j++) 
            {
                pin >> doc_id >> wt >> totalToken >> loc_start;
                string doc = "doc" + to_string(doc_id);
                bool exists = false;

                //save the values into the accumulator
                for(int k = 0; k < accumulator.size(); k++) 
                {
                    if(accumulator[k].document == doc){
                        accumulator[k].wt += wt;
                        exists = true;
                        break;
                        cout << "document match for " << doc << endl;
                    }
                }
                if(!exists) {
                    accumulator.push_back({doc, wt});
                }
            }
        }
        
        //This is if no document is found to have the query
        //if(!found)
            //cout << "no docs" << endl;

    }
    //Call sort with my compare function created
    sort(accumulator.begin(), accumulator.end(), compareWT);

    //open the map file
    ifstream min("output/map.txt");

    //If there are not 10 entries in the accumulator
    //Output the remaining 10 lines as "No more matching documents!"
    if (accumulator.size() < 10) 
    {
        for(int i = 0; i < accumulator.size(); i++) 
        {
            string doc_number = "";
            string doc_name = "";

            min.clear();
            min.seekg(0, std::ios::beg);
            string full_doc = accumulator[i].document;
            string numbers = "";
            for (char c : full_doc) {
                if (isdigit(c))
                    numbers += c;
            }
            //After obtaining just the number of the doc, then find it in map.txt
            int number = stoi(numbers);
            streampos pos = number;
            pos = pos * 17;
            min.seekg(pos, ios::beg);

            min >> doc_number >> doc_name;
            cout << accumulator[i].document << " " << doc_name << " " << accumulator[i].wt << endl;
        }
        for(int i = 0; i < 10-accumulator.size(); i++) {
            cout << "doc" << endl;
            cout << "No No matches!" << endl;
        } 
    }
    //If there are 10 documents in accumulator, then output them
    else 
    {
        for(int i = 0; i < 10; i++) 
        {
            string doc_number = "";
            string doc_name = "";

            min.clear();
            min.seekg(0, std::ios::beg);
            string full_doc = accumulator[i].document;
            string numbers = "";
            for (char c : full_doc) {
                if (isdigit(c))
                    numbers += c;
            }
            //After obtaining just the number of the doc, then find it in map.txt
            int number = stoi(numbers);
            streampos pos = number;
            pos = pos * 17;
            min.seekg(pos, ios::beg);

            min >> doc_number >> doc_name;
            cout << accumulator[i].document << " " << doc_name << " " << accumulator[i].wt << endl;
        }
    }
}

int main(int argc, char **argv)
{ 
    //create the accumulator vector of Bucket and open the temp file
    vector<Bucket> accumulator;
    //ofstream dout("input.html");
    ofstream dout("/tmp/testfile.html");

    if (argc < 2) {
      cout << "there isn't enough command args " << endl;
      return 1;
    }

    int i = 2;
    string arg = argv[1];
    string arg2 = argv[2];

    //cout << arg <<  endl;
    //cout << "word is " << arg2 << endl;

    string inputDir = "";

   while(argv[i] != NULL) {
      
      string arg2 = argv[i];

      if (arg2.find(' ') != string::npos) {
            arg2 = '"' + arg2 + '"';
      }

      dout << arg2 << endl;
      i++;
   }

   //manually set input directory
   inputDir = "output";
    //set path and name to dict and post
    string dict = inputDir + "/" + "dict.txt";
    string post = inputDir + "/" + "post.txt";    

   if (!arg.empty()) {
      if((yyin = fopen(argv[1],"r"))==NULL)
         cout << "\n Error opening input file \n";
   }
    
    //flex retrieve.flex
    //g++ -o retrieve lex.yy.c hashtable.cpp -lfl
    //./retrieve (-q) [words] (-d) (dir)

    yylex();

   if (stemmedToken != "")
      quoteQueries.push_back(stemmedToken);

   //for (int d = 0; d < quoteQueries.size(); d++)
      //cout << "index " << d << ": " << quoteQueries[d] << endl;
   //for (int e = 0; e < query.size(); e++)
      //cout << "word " << e << ": " << query[e] << endl;

    //call the query handler
    handleQuery(dict, post, accumulator);

    
}